name: Setup boilerplate
inputs:
  renderer-template:
    description: Define what vite template should be used to create renderer in case if renderer package doesn't exist
    required: false
    default: ''


runs:
  using: "composite"
  steps:
    - if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        Xvfb :99 -screen 0 1280x960x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Check if renderer directory exists
      id: check-renderer
      run: >-
        if [ -d "packages/renderer" ]; then
          echo "RENDERER_EXIST=true" >> $GITHUB_OUTPUT
        else
          echo "RENDERER_EXIST=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - run: |
        pnpm run create-renderer -- -- --template ${{inputs.renderer-template}}
        pnpm start --workspace @app/integrate-renderer
      shell: bash
      if: inputs.renderer-template != '' && steps.check-renderer.outputs.RENDERER_EXIST == 'false'

    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
          ~/.cache/electron
          ~/.cache/electron-builder
        key: deps-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          deps-${{ runner.os }}-

    - name: Install Dependencies
      run: >-
        if [ "${{ steps.check-renderer.outputs.RENDERER_EXIST }}" == "true" ] && [ -f "pnpm-lock.yaml" ]; then
          pnpm install --frozen-lockfile
        else
          pnpm install
        fi
      shell: bash
      env:
        # 确保Electron能正确下载
        ELECTRON_CACHE: ~/.cache/electron
        ELECTRON_BUILDER_CACHE: ~/.cache/electron-builder

    - name: Verify Electron Installation
      run: |
        # 检查Electron是否正确安装，如果没有则重新安装
        if ! pnpm exec electron --version 2>/dev/null; then
          echo "Electron installation failed, reinstalling..."
          pnpm rebuild electron
        fi
      shell: bash
      env:
        ELECTRON_CACHE: ~/.cache/electron
        ELECTRON_BUILDER_CACHE: ~/.cache/electron-builder
