name: Compile and test

on:
  workflow_call:
    inputs:
      app-version:
        required: true
        type: string
      distribution-channel:
        required: true
        type: string

defaults:
  run:
    shell: 'bash'

permissions:
  contents: read

env:
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/

jobs:
  typeckeck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/init-template-with-renderer
        name: Setup boilerplate
        with:
          renderer-template: react-swc-ts
      - run: pnpm run typecheck

  compile:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/init-template-with-renderer
        name: Setup boilerplate
        with:
          renderer-template: react-swc-ts

      - run: pnpm version "${{inputs.app-version}}" --no-git-tag-version

      - name: Build for PR validation
        if: inputs.distribution-channel == 'pr-validation'
        run: pnpm run build

      - name: Build for testing (no publish)
        if: inputs.distribution-channel == 'pr-validation'
        run: |
          pnpm run build
          pnpm exec electron-builder build --config electron-builder.mjs -p never
        env:
          VITE_DISTRIBUTION_CHANNEL: ${{inputs.distribution-channel}}

      - name: Build and publish release
        if: inputs.distribution-channel != 'pr-validation'
        run: pnpm run compile
        env:
          VITE_DISTRIBUTION_CHANNEL: ${{inputs.distribution-channel}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npx playwright test
        if: matrix.os != 'ubuntu-latest'

      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npx playwright test
        if: matrix.os == 'ubuntu-latest'

      - uses: actions/attest-build-provenance@v2
        if: inputs.distribution-channel != 'pr-validation'
        with:
          subject-path: "dist/root*, dist/latest*.yml"

      - name: Upload compiled app
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{inputs.distribution-channel}}
          path: dist
