# Main branch CI workflow - runs on push to main
name: Main Branch CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: main-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  main-ci:
    name: Main Branch CI - TypeScript + React
    uses: ./.github/workflows/ci.yml
    with:
      distribution-channel: react-swc-ts
    permissions:
      contents: write
      id-token: write
      attestations: write
    secrets: inherit

  dependabot:
    permissions:
      contents: write
      pull-requests: write
    needs:
      - main-ci
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
