# PR validation workflow - only runs on pull requests
name: PR Validation

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate-pr:
    name: Validate PR - TypeScript + React
    uses: ./.github/workflows/compile-and-test.yml
    with:
      app-version: "0.0.0-pr.${{ github.event.number }}"
      distribution-channel: pr-validation
    permissions:
      contents: read

  dependabot:
    permissions:
      contents: write
      pull-requests: write
    needs:
      - validate-pr
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
